/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUpgradeRouteImport } from './routes/_app/upgrade'
import { Route as AppSuporteRouteImport } from './routes/_app/suporte'
import { Route as AppHistoricoRouteImport } from './routes/_app/historico'
import { Route as AppFavoritosRouteImport } from './routes/_app/favoritos'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiAdminRunMigrationRouteImport } from './routes/api/admin/run-migration'
import { Route as AppModulosIdRouteImport } from './routes/_app/modulos.$id'
import { Route as ApiPublicCacktoWebhookRouteImport } from './routes/api/public/cackto/webhook'
import { Route as ApiPublicCacktoDiagRouteImport } from './routes/api/public/cackto/diag'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUpgradeRoute = AppUpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => AppRoute,
} as any)
const AppSuporteRoute = AppSuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoricoRoute = AppHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AppRoute,
} as any)
const AppFavoritosRoute = AppFavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiAdminRunMigrationRoute = ApiAdminRunMigrationRouteImport.update({
  id: '/api/admin/run-migration',
  path: '/api/admin/run-migration',
  getParentRoute: () => rootRouteImport,
} as any)
const AppModulosIdRoute = AppModulosIdRouteImport.update({
  id: '/modulos/$id',
  path: '/modulos/$id',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCacktoWebhookRoute = ApiPublicCacktoWebhookRouteImport.update({
  id: '/api/public/cackto/webhook',
  path: '/api/public/cackto/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCacktoDiagRoute = ApiPublicCacktoDiagRouteImport.update({
  id: '/api/public/cackto/diag',
  path: '/api/public/cackto/diag',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/favoritos': typeof AppFavoritosRoute
  '/historico': typeof AppHistoricoRoute
  '/suporte': typeof AppSuporteRoute
  '/upgrade': typeof AppUpgradeRoute
  '/modulos/$id': typeof AppModulosIdRoute
  '/api/admin/run-migration': typeof ApiAdminRunMigrationRoute
  '/api/public/cackto/diag': typeof ApiPublicCacktoDiagRoute
  '/api/public/cackto/webhook': typeof ApiPublicCacktoWebhookRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/favoritos': typeof AppFavoritosRoute
  '/historico': typeof AppHistoricoRoute
  '/suporte': typeof AppSuporteRoute
  '/upgrade': typeof AppUpgradeRoute
  '/': typeof AppIndexRoute
  '/modulos/$id': typeof AppModulosIdRoute
  '/api/admin/run-migration': typeof ApiAdminRunMigrationRoute
  '/api/public/cackto/diag': typeof ApiPublicCacktoDiagRoute
  '/api/public/cackto/webhook': typeof ApiPublicCacktoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/favoritos': typeof AppFavoritosRoute
  '/_app/historico': typeof AppHistoricoRoute
  '/_app/suporte': typeof AppSuporteRoute
  '/_app/upgrade': typeof AppUpgradeRoute
  '/_app/': typeof AppIndexRoute
  '/_app/modulos/$id': typeof AppModulosIdRoute
  '/api/admin/run-migration': typeof ApiAdminRunMigrationRoute
  '/api/public/cackto/diag': typeof ApiPublicCacktoDiagRoute
  '/api/public/cackto/webhook': typeof ApiPublicCacktoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/favoritos'
    | '/historico'
    | '/suporte'
    | '/upgrade'
    | '/modulos/$id'
    | '/api/admin/run-migration'
    | '/api/public/cackto/diag'
    | '/api/public/cackto/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/dashboard'
    | '/favoritos'
    | '/historico'
    | '/suporte'
    | '/upgrade'
    | '/'
    | '/modulos/$id'
    | '/api/admin/run-migration'
    | '/api/public/cackto/diag'
    | '/api/public/cackto/webhook'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/favoritos'
    | '/_app/historico'
    | '/_app/suporte'
    | '/_app/upgrade'
    | '/_app/'
    | '/_app/modulos/$id'
    | '/api/admin/run-migration'
    | '/api/public/cackto/diag'
    | '/api/public/cackto/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiAdminRunMigrationRoute: typeof ApiAdminRunMigrationRoute
  ApiPublicCacktoDiagRoute: typeof ApiPublicCacktoDiagRoute
  ApiPublicCacktoWebhookRoute: typeof ApiPublicCacktoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/upgrade': {
      id: '/_app/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof AppUpgradeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suporte': {
      id: '/_app/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof AppSuporteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/historico': {
      id: '/_app/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AppHistoricoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/favoritos': {
      id: '/_app/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof AppFavoritosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/admin/run-migration': {
      id: '/api/admin/run-migration'
      path: '/api/admin/run-migration'
      fullPath: '/api/admin/run-migration'
      preLoaderRoute: typeof ApiAdminRunMigrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/modulos/$id': {
      id: '/_app/modulos/$id'
      path: '/modulos/$id'
      fullPath: '/modulos/$id'
      preLoaderRoute: typeof AppModulosIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/cackto/webhook': {
      id: '/api/public/cackto/webhook'
      path: '/api/public/cackto/webhook'
      fullPath: '/api/public/cackto/webhook'
      preLoaderRoute: typeof ApiPublicCacktoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cackto/diag': {
      id: '/api/public/cackto/diag'
      path: '/api/public/cackto/diag'
      fullPath: '/api/public/cackto/diag'
      preLoaderRoute: typeof ApiPublicCacktoDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFavoritosRoute: typeof AppFavoritosRoute
  AppHistoricoRoute: typeof AppHistoricoRoute
  AppSuporteRoute: typeof AppSuporteRoute
  AppUpgradeRoute: typeof AppUpgradeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppModulosIdRoute: typeof AppModulosIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFavoritosRoute: AppFavoritosRoute,
  AppHistoricoRoute: AppHistoricoRoute,
  AppSuporteRoute: AppSuporteRoute,
  AppUpgradeRoute: AppUpgradeRoute,
  AppIndexRoute: AppIndexRoute,
  AppModulosIdRoute: AppModulosIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiAdminRunMigrationRoute: ApiAdminRunMigrationRoute,
  ApiPublicCacktoDiagRoute: ApiPublicCacktoDiagRoute,
  ApiPublicCacktoWebhookRoute: ApiPublicCacktoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
